// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace SeleniumFramework.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("OwnerRegistration")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class OwnerRegistrationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "OwnerRegistration", "As a system user, I want to register an owner so that the system can maintain a r" +
                "ecord of clinic clients.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "OwnerRegistration.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/OwnerRegistration.feature.ndjson", 21);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Successfully register a new owner with valid data")]
        [global::NUnit.Framework.CategoryAttribute("FindOwnersPage")]
        public async global::System.Threading.Tasks.Task SuccessfullyRegisterANewOwnerWithValidData()
        {
            string[] tagsOfScenario = new string[] {
                    "FindOwnersPage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successfully register a new owner with valid data", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.WhenAsync("I click the \"Add Owner\" Link.", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.AndAsync("I fill in the owner valid data.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
 await testRunner.AndAsync("I click the \"Add Owner Submit\" button on the form.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.ThenAsync("I should be redirected to the Owner Information page.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
 await testRunner.AndAsync("I should see the details of the newly created owner.", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Verify field validation rules")]
        [global::NUnit.Framework.CategoryAttribute("NegativeOwnerRegistration")]
        [global::NUnit.Framework.CategoryAttribute("FindOwnersPage")]
        [global::NUnit.Framework.TestCaseAttribute("First Name", "", "Mandatory field can\'t be empty", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("First Name", "A", "Below minimum length (2 characters)", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("First Name", "John123", "English alphabet only (No numbers)", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("First Name", "Иван", "English alphabet only (No Cyrillic)", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("Last Name", "", "Mandatory field can\'t be empty", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("Last Name", "B", "Below minimum length (2 characters)", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("Last Name", "Smith!", "English alphabet only (No special characters)", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("Last Name", "Иванов", "English alphabet only (No Cyrillic)", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "", "Mandatory field can\'t be empty", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "C", "Below minimum length (2 characters)", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "New York 1", "English alphabet only (No numbers)", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("City", "София", "English alphabet only (No Cyrillic)", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("Address", "", "Mandatory field can\'t be empty", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("Address", "София", "English alphabet only (No Cyrillic)", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "", "Mandatory field can\'t be empty", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "12345678901", "Maximum 10 digits allowed", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "123-456-789", "Digits only (No hyphens/special characters)", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("Telephone", "00000000000", "Length violation (11 digits)", "18", null)]
        public async global::System.Threading.Tasks.Task VerifyFieldValidationRules(string field, string value, string reason, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NegativeOwnerRegistration",
                    "FindOwnersPage"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Field", field);
            argumentsOfScenario.Add("Value", value);
            argumentsOfScenario.Add("Reason", reason);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Verify field validation rules", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
 await testRunner.WhenAsync("I click the \"Add Owner\" Link.", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
 await testRunner.AndAsync(string.Format("I enter \"{0}\" into the \"{1}\" owner form field", value, field), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("I click the \"Add Owner Submit\" button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.ThenAsync(string.Format("I should see a warning message for the owner \"{0}\" field", field), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
